name: run-tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [8.0]
                dependency-version: [prefer-lowest, prefer-stable]

        name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip
                    coverage: none

            -   name: Install dependencies
                run: composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

            -   name: Install unoserver and libreoffice
                run: |
                     python -m pip install --upgrade pip
                     sudo apt update
                     sudo apt-get install -y libreoffice
                     sudo pip install unoserver

            -   name: Execute tests
                run: vendor/bin/phpunit
